#!/usr/bin/bash
# Cleaning the case before running
rm -r {1..5}
rm -r postProcessing/

#Adding the settings for pure advection 
sed -i "s/DT 0.01;/DT 0;/g" ./constant/transportProperties
sed -i "s/uniform (0 0 0)/uniform (1 0 0)/g" ./0/U

# Creating a directory to store all the data files 
mkdir ../data-padv

# Making the mesh and setting the fields 
blockMesh
setFields

COUNTER=0
SCHEMES=("QUICK" "upwind" "linearUpwind" "quadratic" "cubic" "vanLeer" "QUICK")
#echo ${SCHEMES[$((4))]}
for I in {0..5}
do 

    sed -i "s/${SCHEMES[${COUNTER}]} grad(T)/${SCHEMES[$((COUNTER+1))]} grad(T)/g"\
    ./system/fvSchemes
    scalarTransportFoam
    for J in {1..5}
    do
        # copying the data file from each timestep folder to data folder
        NAME="time-${J}-dt-${SCHEMES[$((COUNTER+1))]}.xy"
        cp ./postProcessing/singleGraph/${J}/line_T.xy $FOAM_RUN/openfoam-cases/pitzDaily-scalarFoam/data-padv/${NAME}
    done
    rm -r {1..5}
    rm -r postProcessing
    COUNTER=$((COUNTER+1))
done

#Reverting the settings
sed -i "s/DT 0;/DT 0.01;/g" ./constant/transportProperties
sed -i "s/uniform (1 0 0)/uniform (0 0 0)/g" ./0/U